In [28]:
!pip install geopandas

Requirement already satisfied: geopandas in /usr/local/lib/python3.7/dist-packages (0.9.0)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.1.5)
Requirement already satisfied: fiona>=1.8 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.8.20)
Requirement already satisfied: pyproj>=2.2.0 in /usr/local/lib/python3.7/dist-packages (from geopandas) (3.1.0)
Requirement already satisfied: shapely>=1.6 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.7.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->geopandas) (2.8.1)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->geopandas) (1.19.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->geopandas) (2018.9)
Requirement already satisfied: six>=1.7 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (1.15.0)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (0.7.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (2021.5.30)
Requirement already satisfied: munch in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (57.2.0)
Requirement already satisfied: attrs>=17 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (21.2.0)
Requirement already satisfied: click-plugins>=1.0 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (1.1.1)
Requirement already satisfied: click>=4.0 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (7.1.2)

In [29]:
import geopandas
import pandas as pd

In [30]:
routes = geopandas.read_file("DummyData.shp")

In [31]:
df = pd.DataFrame(routes)
df.drop("id", axis = 1)

    time                                           geometry
0   15.0  LINESTRING (33.79315 -13.96266, 33.79367 -13.9...
1    5.0  LINESTRING (33.79629 -13.95885, 33.79784 -13.9...
2   10.0  LINESTRING (33.79687 -13.96107, 33.79609 -13.9...
3   10.0  LINESTRING (33.79294 -13.96266, 33.79216 -13.9...
4   10.0  LINESTRING (33.79342 -13.95737, 33.79165 -13.9...
5   15.0  LINESTRING (33.78912 -13.96029, 33.78866 -13.9...
6   15.0  LINESTRING (33.79024 -13.96397, 33.78981 -13.9...
7   15.0  LINESTRING (33.79334 -13.96274, 33.79231 -13.9...
8   10.0  LINESTRING (33.79345 -13.95762, 33.79276 -13.9...
9   10.0  LINESTRING (33.79626 -13.95885, 33.79506 -13.9...
10  25.0  LINESTRING (33.79692 -13.96105, 33.79618 -13.9...
11  15.0  LINESTRING (33.79406 -13.96670, 33.79305 -13.9...
12  10.0  LINESTRING (33.79041 -13.96386, 33.79047 -13.9...
13  20.0  LINESTRING (33.79317 -13.96274, 33.79543 -13.9...
14  15.0  LINESTRING (33.79661 -13.96800, 33.79684 -13.9...
15  25.0  LINESTRING (33.79411 -13.96678, 33.79308 -13.9...
16  10.0  LINESTRING (33.79047 -13.96394, 33.79053 -13.9...
17  15.0  LINESTRING (33.79320 -13.96272, 33.79363 -13.9...
18  60.0  LINESTRING (33.79328 -13.95765, 33.79294 -13.9...
19  70.0  LINESTRING (33.79692 -13.95392, 33.79672 -13.9...
20  30.0  LINESTRING (33.79044 -13.96383, 33.79053 -13.9...
21   NaN  LINESTRING (33.79859 -13.96940, 33.79773 -13.9...
22  30.0  LINESTRING (33.79853 -13.96940, 33.79773 -13.9...
23   5.0  LINESTRING (33.79710 -13.96110, 33.79761 -13.9...
24  20.0  LINESTRING (33.79801 -13.95960, 33.79862 -13.9...
25  20.0  LINESTRING (33.79325 -13.96277, 33.79365 -13.9...
26  15.0  LINESTRING (33.79337 -13.95754, 33.79274 -13.9...
27  20.0  LINESTRING (33.79038 -13.96405, 33.79053 -13.9...
28  15.0  LINESTRING (33.79437 -13.96558, 33.79692 -13.9...
29  15.0  LINESTRING (33.79862 -13.96959, 33.79773 -13.9...
30  15.0  LINESTRING (33.79329 -13.96275, 33.78865 -13.9...
31  25.0  LINESTRING (33.78911 -13.96028, 33.79043 -13.9...
32  40.0  LINESTRING (33.79693 -13.95375, 33.79670 -13.9...

In [61]:
data = []
for i in range(33):
  linestring = df.iloc[i, 2]
  time = df.iloc[i,1]
  coordinates = list(df.iloc[i, 2].coords)
  coorX1 = round(coordinates[0][0], 3)
  coorY1 = round(coordinates[0][1], 3)

  coorX2 = round(coordinates[-1][0], 3)
  coorY2 = round(coordinates[-1][1], 3)
  data.append([time, [coorX1, coorY1] , [coorX2, coorY2]])

In [70]:
df = pd.DataFrame(data)
df.rename(columns = {0:"Time", 1:"Starting coordinates", 2: "Finishing coordinates"})

    Time Starting coordinates Finishing coordinates
0   15.0    [33.793, -13.963]     [33.796, -13.959]
1    5.0    [33.796, -13.959]     [33.797, -13.961]
2   10.0    [33.797, -13.961]     [33.793, -13.963]
3   10.0    [33.793, -13.963]     [33.793, -13.958]
4   10.0    [33.793, -13.957]      [33.789, -13.96]
5   15.0     [33.789, -13.96]      [33.79, -13.964]
6   15.0     [33.79, -13.964]     [33.793, -13.963]
7   15.0    [33.793, -13.963]     [33.793, -13.958]
8   10.0    [33.793, -13.958]     [33.796, -13.959]
9   10.0    [33.796, -13.959]     [33.797, -13.961]
10  25.0    [33.797, -13.961]     [33.794, -13.967]
11  15.0    [33.794, -13.967]      [33.79, -13.964]
12  10.0     [33.79, -13.964]     [33.793, -13.963]
13  20.0    [33.793, -13.963]     [33.797, -13.968]
14  15.0    [33.797, -13.968]     [33.794, -13.966]
15  25.0    [33.794, -13.967]      [33.79, -13.964]
16  10.0     [33.79, -13.964]     [33.793, -13.963]
17  15.0    [33.793, -13.963]     [33.793, -13.958]
18  60.0    [33.793, -13.958]     [33.797, -13.954]
19  70.0    [33.797, -13.954]      [33.79, -13.964]
20  30.0     [33.79, -13.964]     [33.794, -13.967]
21  20.0    [33.799, -13.969]     [33.795, -13.963]
22  30.0    [33.799, -13.969]     [33.797, -13.961]
23   5.0    [33.797, -13.961]     [33.795, -13.959]
24  20.0     [33.798, -13.96]     [33.797, -13.955]
25  20.0    [33.793, -13.963]      [33.789, -13.96]
26  15.0    [33.793, -13.958]      [33.79, -13.964]
27  20.0     [33.79, -13.964]     [33.794, -13.966]
28  15.0    [33.794, -13.966]      [33.799, -13.97]
29  15.0     [33.799, -13.97]     [33.793, -13.963]
30  15.0    [33.793, -13.963]     [33.789, -13.961]
31  25.0     [33.789, -13.96]     [33.797, -13.954]
32  40.0    [33.797, -13.954]     [33.793, -13.958]

     0     1                                                  2
0    0  15.0  [(33.79315209394937, -13.962660591641441), (33...
1    1   5.0  [(33.79629246530465, -13.95884760191348), (33....
2    2  10.0  [(33.79686604911383, -13.961074172921425), (33...
3    3  10.0  [(33.79293700002092, -13.962660591641441), (33...
4    4  10.0  [(33.79342454625873, -13.957372486776121), (33...
5    5  15.0  [(33.78912266768984, -13.960294875515348), (33...
6    6  15.0  [(33.790241156117744, -13.963968683072475), (3...
7    7  15.0  [(33.793338508687356, -13.962744087061028), (3...
8    8  10.0  [(33.79345322544919, -13.957622978691225), (33...
9    9  10.0  [(33.796263786114196, -13.95884760191348), (33...
10  10  25.0  [(33.79692340749475, -13.961046340916578), (33...
11  11  15.0  [(33.794055488448834, -13.96669616897909), (33...
12  12  10.0  [(33.7904132312605, -13.963857356431275), (33....
13  13  20.0  [(33.7931664335446, -13.962744087061028), (33....
14  14  15.0  [(33.7966079363997, -13.968004237497937), (33....
15  15  25.0  [(33.79411284682975, -13.966779662936247), (33...
16  16  10.0  [(33.79047058964143, -13.96394085141721), (33....
17  17  15.0  [(33.79319511273505, -13.962716255257863), (33...
18  18  60.0  [(33.79328115030643, -13.957650811109424), (33...
19  19  70.0  [(33.79692340749475, -13.953921237128057), (33...
20  20  30.0  [(33.79044191045096, -13.963829524762563), (33...
21  21  20.0  [(33.79858680054139, -13.969395791597686), (33...
22  22  30.0  [(33.79852944216048, -13.969395791597686), (33...
23  23   5.0  [(33.79709548263751, -13.961102004922912), (33...
24  24  20.0  [(33.7980132167322, -13.959599072033306), (33....
25  25  20.0  [(33.79325247111597, -13.962771918860838), (33...
26  26  15.0  [(33.79336718787781, -13.957539481416429), (33...
27  27  20.0  [(33.790384552070044, -13.964052178018083), (3...
28  28  15.0  [(33.79437095954389, -13.965582913325322), (33...
29  29  15.0  [(33.79861547973185, -13.969590608500777), (33...
30  30  15.0  [(33.79329109760744, -13.962752769153747), (33...
31  31  25.0  [(33.78910547244789, -13.960284339180106), (33...
32  32  40.0  [(33.796929371784586, -13.953753808356675), (3...